### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by liudoong** [pymc-devs/pytensor#208]
### Describe the issue:

Tried to update the latest version, the error message is reported, please see error message section.

### Reproducable code example:

```python
pip3 install pytensor --update
```

### Error message:

```shell
<details>
pytensor/scan/scan_perform.c:6:10: fatal error: 'Python.h' file not found
      #include "Python.h"
               ^~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pytensor
Failed to build pytensor
ERROR: Could not build wheels for pytensor, which is required to install pyproject.toml-based projects
</details>
```

### PyTensor version information:

<details>
2.9.1
</details>

**Comment by maresb** [comment]
Hi! We strongly recommend installing PyTensor via Mamba (or Conda) so that you get an environment with all the necessary libraries installed.

**Comment by nikisix** [comment]
Ok, but what are the required libraries for those of us committed to pip?

**Comment by ricardoV94** [comment]
> Ok, but what are the required libraries for those of us committed to pip?

On linux not much. I think the wheel these days already includes the Scan cython extension that was behind the error on the top message. So you should be able to pip install and help PyTensor find the clang compiler and blas directories if it can't by default. The detection was also improved since then. If you don't intend to use the C backend, you can just set `pytensor.config.cxx = ''`. 

If you have a more specific setup/problem let us know. Keep in mind that we usually push people towards conda because for most users it's a simple and good solution, and because we don't have the manpower to individually assist too many people.
