### ISSUE TITLE
Provide pyodide packages

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pytensor#285]
### Description

Would be great if we could `pip install pytensor` on pyodide. We can build without the cython extension and it works, however, we should create proper pyodide packages https://pyodide.org/en/0.19.1/development/new-packages.html.

**Comment by twiecki** [comment]
They need to be non-binary / universal as I found out. But apparently this isn't possible with extensions...

**Comment by twiecki** [comment]
OK, removing the Extension in setup.py allowed me to build a universal wheel:
```
    setup(
        name=NAME,
        version="2.11.2", #versioneer.get_version(),
        cmdclass=versioneer.get_cmdclass(),
        #ext_modules=[
        #    Extension(
        #        name="pytensor.scan.scan_perform",
        #        sources=["pytensor/scan/scan_perform.pyx"],
        #        include_dirs=[numpy.get_include()],
        #    ),
        #],
    )
```

And then:
`python setup.py bdist_wheel --universal`
Followed by `twine upload dist/pytensor-2.11.2-cp310-cp310-macosx_11_0_arm64.whl`.

Would be nice to somehow automate that process, easiest would be a separate setup.py that doesn't have the Extension (which is optional in Python mode).

But with this, we get native PyMC running in the browser:
<img width="310" alt="image" src="https://user-images.githubusercontent.com/674200/236408416-41830ba7-6967-49ee-9826-f93164dd36c9.png">

**Comment by lucianopaz** [comment]
Did you just upload a universal wheel to PYPI and not to test-pypi? This is bad and we shouldn't do it. [Wheels will always have precedence over source distributions](https://stackoverflow.com/questions/51527148/pip-install-and-platform-specific-wheels). We build and supply wheels for some platforms and OS versions. If a user is using a different version of the OS or a different platform, calling `pip install` will grab the wheel, which will not include the compiled extensions! That means that said users will end up with an incomplete installation (it looks like they might be missing the scan with the C linker?). I strongly prefer them to get the full package but compiling it from source. That means that we should remove the universal wheel you added as soon as possible, so that users don't get faulty installations.

**Comment by twiecki** [comment]
@lucianopaz Thanks for pointing that out, I deleted the wheel. Any idea for how to get non-binary wheels for pyodide only then?

**Comment by lucianopaz** [comment]
[This](https://pyodide.org/en/0.19.1/development/new-packages.html) seems to have the instructions for building the pyodide package. I've never used it, but they say that they have a [toolchain that could build the js stuff for us](https://pyodide.org/en/0.19.1/development/new-packages.html#building-the-package-and-investigating-issues). I have no idea where it gets uploaded afterwards.

**Comment by twiecki** [comment]
OK, building a proper pyodide package from the source you pointed to seems like the proper way to go. I gave it an honest effort but failed to `make` pyodide (https://github.com/pyodide/pyodide/issues/3829).

**Comment by twiecki** [comment]
OK, while I got a pyodide package to work, there is no way to serve it, so we can't `pip install` it. So universal wheels is the easiest and most user-friendly way to go.

I actually don't think that having non-binary wheels up on PyPI is a big deal. By default, the binary versions will get installed, and where that's not the case, the user gets a big fat warning. wdyt @lucianopaz?

**Comment by twiecki** [comment]
Oh, we can also just add the cython-compiled c-file to the package as well, so it's actually not an issue!

**Comment by ricardoV94** [comment]
@twiecki shall we close this issue or is there stuff we could/should do still?

**Comment by ricardoV94** [comment]
What is the feature request exactly?

**Comment by twiecki** [comment]
Ideally we figure out how to upload universal wheels when we release, but that requires a different setup.py and I haven't found a way to make that clean.

**Comment by twiecki** [comment]
And to your question: Request is to be able to pip install pytensor in pyodide/pyscript.

**Comment by lucianopaz** [comment]
We can't make `pytensor` behave as a universal wheel because it has a cython extension. What we need to do, is to add a build step that actually builds `pytensor` using pyodide. The documentation for that is [here](https://pyodide.org/en/stable/development/new-packages.html) and [here](https://pyodide.org/en/stable/development/building-and-testing-packages.html#building-and-testing-packages-out-of-tree), and they reference [numpy's build action for emscripten](https://github.com/numpy/numpy/blob/main/.github/workflows/emscripten.yml). I don't have time to look into this, and it seems challenging, but doable.

**Comment by twiecki** [comment]
It worked without the cython extension.
The other "proper" path is a bit cumbersome as we first need to build it, and then add it to emscripten.

**Comment by twiecki** [comment]
Another solution could be to revert https://github.com/pymc-devs/pytensor/pull/77. I think that would be easiest and most stable. That PR made Cython non-optional which is a down-side, especially as we switch away from C. 

How do people feel about that? CC @ricardoV94

**Comment by ricardoV94** [comment]
Is there a way to have a `pip install pytensor[no_c]` which is not default and does not require Cython?

**Comment by twiecki** [comment]
I think that should work.
